### ISSUE TITLE
[Bug]  Unrecognized Doris type DATETIMEV2

### ISSUE THREAD

**Issue by milton4code** [apache/doris-spark-connector#102]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

spark-doris-connector-2.3_2.11  1.1.0

### What's Wrong?

1. Exception in thread "main" org.apache.doris.spark.exception.DorisException: Unrecognized Doris type DATETIMEV2

### What You Expected?

should sport DATETIMEV2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
doris must be version 2.0 or above and spark connector version 1.2.0
