### ISSUE TITLE
[Bug] No Doris FE is available when fe use https

### ISSUE THREAD

**Issue by fsilent** [apache/doris-spark-connector#114]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris 1.2.3, master

### What's Wrong?

when fe switch https then use spark connector while throw error
java.io.IOException: Failed to get response from Doris
![image](https://github.com/apache/doris-spark-connector/assets/9815890/7f32810e-c62c-467d-9b4d-cbad531e8b26)

### What You Expected?

execute spark connector success

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gnehil** [comment]
Can you show the configuration parameters？You can contact me via WeChat for details，My WeChat account is `gnehil489`.

**Comment by JNSimba** [comment]
Already supported, you can use the latest spark connector
