### ISSUE TITLE
[Feature]  缺乏详细参数文档

### ISSUE THREAD

**Issue by melin** [apache/doris-spark-connector#115]
spark 读写doris，有哪些参数，缺少详细文档，需要看代码。

**Comment by baishaoisde** [comment]
You can take a look at the official website this page, whether it meets your needs:
https://doris.apache.org/zh-CN/docs/dev/ecosystem/spark-doris-connector#%E9%80%9A%E7%94%A8%E9%85%8D%E7%BD%AE%E9%A1%B9

**Comment by gnehil** [comment]
The effect is the same with or without the doris prefix, welcome to submit pr to improve the document.

**Comment by xinxingi** [comment]
I have submitted related document optimization
