### ISSUE TITLE
[Bug] cannot use bitmap to doris by doris spark connector

### ISSUE THREAD

**Issue by fanjia1024** [apache/doris-spark-connector#129]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

<dependency>
            <groupId>org.apache.doris</groupId>
            <artifactId>spark-doris-connector-3.2_2.12</artifactId>
            <version>1.3.0</version>
        </dependency>

### What's Wrong?

use the official documentation to write bitmap in spark df mode use bitmap_from_array function to write data,like this 
    df.write.format("doris")
      .option("doris.table.identifier", s"$tableName")
      .option("doris.fenodes", s"$url:$sql")
      .option("user", s"$username")
      .option("password", s"$password")
      .option("sink.batch.size", 100)
      .option("sink.max-retries", 3)
      .option("doris.ignore-type", "bitmap")
      .option("doris.deserialize.arrow.async", true)
      .option("doris.deserialize.queue.size", 64)
      .option("sink.properties.column_separator", "|")
      .option("sink.properties.format", "json")
      //其它选项
      //指定你要写入的字段
      .option("doris.write.fields", fieldList)
      .save()
fieldList=tag_id, UPDATED_TIME, tag_value, user_ids,CREATED_TIME, UPDATED_BY ,user_id=bitmap_from_array(user_ids)

### What You Expected?

connector can support this function like bitmap_from_array 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fanjia1024** [comment]
use another way

**Comment by eternal-heart-k** [comment]
> use another way

Hi, could you please describe in detail the feasible method for Spark to write the bitmap type field of Doris? I have also encountered this problem recently

**Comment by eternal-heart-k** [comment]
> > use another way
> 
> Hi, could you please describe in detail the feasible method for Spark to write the bitmap type field of Doris? I have also encountered this problem recently

I have found a solution, ignore it~
