### ISSUE TITLE
[Bug]https://repo1.maven.org/maven2/org/apache/doris/spark-doris-connector-3.2_2.12/1.3.0/spark-doris-connector-3.2_2.12-1.3.0.pom: expected='1.3.0 found='1.3.0-SNAPSHOT'

### ISSUE THREAD

**Issue by tuoluzhe8521** [apache/doris-spark-connector#170]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

v1.3.0和v1.2.0都有这个问题

### What's Wrong?

中央仓库的pom文件没有更新
<thrift-service.version>1.0.0</thrift-service.version>
<netty.version>4.1.77.Final</netty.version>
<arrow.version>5.0.0</arrow.version>
<spark.major.version>3.1</spark.major.version>
<libthrift.version>0.16.0</libthrift.version>
<project.scm.id>github</project.scm.id>
<fasterxml.jackson.version>2.10.5</fasterxml.jackson.version>
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
<revision>1.2.0-SNAPSHOT</revision>
<scala.version>2.12</scala.version>
<spark.version>3.1.2</spark.version>

### What You Expected?

修改下

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gnehil** [comment]
Is there any impact on usage?

**Comment by tuoluzhe8521** [comment]
> Is there any impact on usage?
when i submit sparksql task，it always give error,like:
:: problems summary ::
:::: WARNINGS
		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.apache.doris#spark-doris-connector-3.2_2.12;1.3.0: java.text.ParseException: inconsistent module descriptor file found in 'https://repo1.maven.org/maven2/org/apache/doris/spark-doris-connector-3.2_2.12/1.3.0/spark-doris-connector-3.2_2.12-1.3.0.pom': bad revision: expected='1.3.0' found='1.3.0-SNAPSHOT'; 

		::::::::::::::::::::::::::::::::::::::::::::::


:::: ERRORS
		central: bad revision found in https://repo1.maven.org/maven2/org/apache/doris/spark-doris-connector-3.2_2.12/1.3.0/spark-doris-connector-3.2_2.12-1.3.0.pom: expected='1.3.0 found='1.3.0-SNAPSHOT'


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: org.apache.doris#spark-doris-connector-3.2_2.12;1.3.0: java.text.ParseException: inconsistent module descriptor file found in 'https://repo1.maven.org/maven2/org/apache/doris/spark-doris-connector-3.2_2.12/1.3.0/spark-doris-connector-3.2_2.12-1.3.0.pom': bad revision: expected='1.3.0' found='1.3.0-SNAPSHOT'; ]
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1458)
	at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:319)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:909)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:191)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:214)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1054)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1063)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by tuoluzhe8521** [comment]
> > Is there any impact on usage?
> > when i submit sparksql task，it always give error,like:
> > :: problems summary ::
> > :::: WARNINGS
> > ::::::::::::::::::::::::::::::::::::::::::::::
> 
> ```
> 	::          UNRESOLVED DEPENDENCIES         ::
> 
> 	::::::::::::::::::::::::::::::::::::::::::::::
> 
> 	:: org.apache.doris#spark-doris-connector-3.2_2.12;1.3.0: java.text.ParseException: inconsistent module descriptor file found in 'https://repo1.maven.org/maven2/org/apache/doris/spark-doris-connector-3.2_2.12/1.3.0/spark-doris-connector-3.2_2.12-1.3.0.pom': bad revision: expected='1.3.0' found='1.3.0-SNAPSHOT'; 
> 
> 	::::::::::::::::::::::::::::::::::::::::::::::
> ```
> 
> :::: ERRORS central: bad revision found in https://repo1.maven.org/maven2/org/apache/doris/spark-doris-connector-3.2_2.12/1.3.0/spark-doris-connector-3.2_2.12-1.3.0.pom: expected='1.3.0 found='1.3.0-SNAPSHOT'
> 
> :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: org.apache.doris#spark-doris-connector-3.2_2.12;1.3.0: java.text.ParseException: inconsistent module descriptor file found in 'https://repo1.maven.org/maven2/org/apache/doris/spark-doris-connector-3.2_2.12/1.3.0/spark-doris-connector-3.2_2.12-1.3.0.pom': bad revision: expected='1.3.0' found='1.3.0-SNAPSHOT'; ] at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1458) at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185) at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:319) at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:909) at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:191) at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:214) at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90) at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1054) at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1063) at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

i submit sparksql task in k8s

**Comment by JNSimba** [comment]
1.3.1 fixed this problem, can you help test it?

**Comment by tuoluzhe8521** [comment]
i meet this problem when i submit sparksql task in k8s,because i can't sovle it. I give up k8s, so i can't test it now
