### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by yongjinhou** [apache/doris-spark-connector#208]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris 1.2
spark 3.2
spark-doris-connector 1.3.1

### What's Wrong?

spark通过connector读取doris中的数据。
如果doris的表包含daev2类型字段，写入数据正常，而读取数据报错：
<img width="1395" alt="image" src="https://github.com/apache/doris-spark-connector/assets/109586248/aa8c0c3a-4f16-4db0-afba-875716be5469">
将datev2类型改为date后，读取数据正常。

### What You Expected?

正常读取数据

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gnehil** [comment]
Doris version 1.2 does not support datev2 type serialization, so the spark connector cannot read this type of data. 
Please upgrade to version 2.0 and above or change the column type to date
