### ISSUE TITLE
[Bug] SaveMode.Overwrite failed write data to doris

### ISSUE THREAD

**Issue by qg-lin** [apache/doris-spark-connector#213]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

spark-doris-connector-3.2_2.12:1.3.2

### What's Wrong?

When use SaveMode.Overwrite to write dataframe, 'No suitable driver found for jdbc'  exception  occured.
![dcc0133c324068c1ef55c4df2b8b11f](https://github.com/apache/doris-spark-connector/assets/37775475/d7e64da5-0957-464c-8f2b-8ab045088067)

### What You Expected?

success write data to doris by SaveMode.Overwrite

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gnehil** [comment]
This is due to missing JDBC driver package.
You need to place the mysql jdbc driver package in the spark classpath, or set the `--jars` option to specify the corresponding jar when executing the `spark-submit` command.
