### ISSUE TITLE
[Enhancement] can provide a json format read data type  like flink-connector  

### ISSUE THREAD

**Issue by gitfortian** [apache/doris-spark-connector#53]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

source data incude chinese word may cause some problem 
Reason: actual column number is less than schema column number.actual number: 10, column separator: [	], line delimiter: [
],
can spark like flink connetor read data by json format to avoid the problem
JSON格式导入
'sink.properties.format' = 'json' 'sink.properties.read_json_by_line' = 'true'

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
Thanks for @gitfortian  , this is already supported, Close
