### ISSUE TITLE
[Bug] not support doris V2 data type 

### ISSUE THREAD

**Issue by lordk911** [apache/doris-spark-connector#93]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

spark-doris-connector-3.2_2.12
doris 1.2.3

### What's Wrong?

org.apache.doris.spark.exception.DorisException: Unrecognized Doris type DATEV2

### What You Expected?

support newly doris data type 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liuchunhua** [comment]
I have the same type of problem

spark-doris-connector-3.1_2.12 branch:master
doris 1.2.3
```
org.apache.doris.spark.exception.DorisException: Unrecognized Doris type DECIMAL128
```

**Comment by JNSimba** [comment]
The problem has been solved and can be upgraded to the latest versions of doris2.X and spark connector
