### ISSUE TITLE
[Bug] column_separator and line_delimiter not support an invisible character

### ISSUE THREAD

**Issue by liuchunhua** [apache/doris-spark-connector#96]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

Doris 1.2.3
doris-spark-connector: master

### What's Wrong?

pyspark3.1.3
``` python
df.write.format("doris")
        .option("doris.table.identifier", "")
        .option("doris.fenodes", "")
        .option("user", "")
        .option("password", "")
        .option("doris.write.fields", ",".join(df.columns))
        .option("doris.sink.batch.size", "20000")
        .option("doris.sink.max-retries", "3")
        .option("doris.sink.properties.format", "csv")
        .option("sink.properties.column_separator", "\\x01")
        .option("sink.properties.line_delimiter", "\\x07")
        .option("doris.sink.batch.interval.ms", "200")
```
stream load csv failed with invisible character

### What You Expected?

like Doris fe
org.apache.doris.analysis.Separator 
convert \x01 and invisible character

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gnehil** [comment]
we are working on this，it will be supported soon

**Comment by JNSimba** [comment]
It has been resolved and can be upgraded to the latest connector
